keys:
  - &penguin age1st5g67qt6x9jsmnwq8e8cp3fdua6fy7gysu38y9g7p5f6w92qctsxwgvq9
  - &altra age1m5s42688lsjkgqh8g66nxfc2vcxmz9v5jyar465zvck2rd8kdq5sd37upe

creation_rules:
  - path_regex: ^secrets/system\.yaml$
    key_groups:
      - age:
          - *penguin
          - *altra

  - path_regex: ^secrets/home\.yaml$
    key_groups:
      - age:
          - *penguin
          - *altra

  - path_regex: ^config/ssh/config\.yaml$
    key_groups:
      - age:
          - *penguin
          - *altra

  - path_regex: ^config/vps/.+$
    key_groups:
      - age:
          - *penguin
          - *altra

