private_config: ENC[AES256_GCM,data:EHRcq+mGW/cqonS1+4Q+uR2jq3oqUMEoREPtEkzqbh3rGxJbIYvNEj33MLLLpngsl1a4d25S60EqK+tZpKxeUq13OlmfX8zvk7kTYUV8E5zWyr/elzGOSoXcfNgBfDiBPm+TlaY=,iv:+eLqK2VMX0TaAyabfVEydUGX7pY3LY2aiovzSJi5xBk=,tag:KPZ1bqtLWoii97+ZcMnHmw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYOWVqVGVkOU16M1cvWmUv
            M0xzMlJ3Z2JrYkNWVFkwNVRseXVwSFBqMG5nCkpTYy9YMmpLc3hnZ1NzYnhTaXpr
            YUJhaTZ1d2llV2d0Tm0vQ3B6cUthR2MKLS0tIDBoR3kxVE5kY09IMHdvdFFKbjda
            SmZoK1NhclNudzdwZFkrdGFpK3ozOUkKUUBGLArtNdTFHEnlP2mVxqNN/G+F1Kw4
            dxY1wXAPN4hhlsEdhY/JGi4AWvDF7CKr0VNskjWB2oka+o7OHKDpwQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1st5g67qt6x9jsmnwq8e8cp3fdua6fy7gysu38y9g7p5f6w92qctsxwgvq9
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaUd6ckI3L0FtbVVhTTd0
            bkRmRFVTeXZmTTFVOGMveW1Ic255T25XM0ZNCmN5NFB3VFZ0ZlRQSmU0d1k1VmtG
            eDhrWVZnb1l2SGtxUGdqK1NmSU9Fa00KLS0tIGtuMFR3c0tkYVVpMURWUnZ2TXpI
            ZWhWRkFpQnZTbTVUL1RSVjh6UFVXT28KIqI4QMT71y//KfBaU9cSNOlUpsuY+DjV
            vOb9SCdw4xpgT779UBJMvScxf1Q0QzoiR0W3P77/NbcR20LueOe+qg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m5s42688lsjkgqh8g66nxfc2vcxmz9v5jyar465zvck2rd8kdq5sd37upe
    lastmodified: "2026-05-23T14:16:22Z"
    mac: ENC[AES256_GCM,data:O+J/hUpz0E2FX2jATA/+dx3pWeIg8FqV3YIalmyEwIf/ZY9vA72lABw8AgiAEkvt3DXjuuTpFBZuHW6eZOzlllSKUJle5swGaMHihZcW2k83gXGz4QGQYVpLC7L2/xodtvYamJLANMbRmF10ZTa+EaXo+2xqooQyLWw1e4QCXGg=,iv:xB4C27Wly5MEpumQA2jgLqVTTTTmoQOf8eTTNI4TSsA=,tag:jEgAnwhWBv88LPmd2DCAig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
