private_config: ENC[AES256_GCM,data:FGDEnQvUrJzlAbxO1ubkMKnwaxsqH0ZMQ15fIZyQ4z1X+IeHoxToDTmnL+GO/QFUUnk8zbXw4kCSxJ9j1GIpB/KINVkRIEdfcQzzOMcYg7EHx9cy/Xb8oa6b5dl+z6gTJ3/Diw0=,iv:ZgN6reveFdMC0c0Cfur1VgwLoCkK4Y9LM6sODMirEOg=,tag:HQHROqsR8qkBWnGPfNXslw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoelloUWtYZThxNVl4L3d6
            aDdYMDRtdVh0ODFHYXBJS1Q4dkd4SnlDTG1ZCjlYeXVxMlg0cFdtT3RhODNmdnBp
            cm0wM0pvemZ2UFh1NFQ5TklqS0lsblEKLS0tIHN2dmJEKzlkbVV6MUhKMi91cXFv
            WWwwdThJUFBITGRtejhjVWl3bk9ET00KhWiGBriV269thUxBSQxNlDdBJJAGgXau
            HdYUlqsFL0yNmXFlFWpNaPCaQesUIH91JXNSwPSbXzKU21loWCfNAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r9eq9v6a0d42wud7whenfv4f29jgfv5t7qpzra0p36d6twsj2dhslppu56
    lastmodified: "2026-05-23T08:41:33Z"
    mac: ENC[AES256_GCM,data:lviv1Q2jmVqbgwIjH4aioORQHZ8QK2v2Que9AjBGuzvbj2m7Um09Zg+kgpzNVpfgI3proJWPLdyi7pIXqctGKTHydxRJAN92eg/p05Fydfh93xqr46CbLYrN8hGkOaYLpqc1g6q3fNTmKQfGA7wtkyKq5UPscSK1lHlh0YXfBgA=,iv:jkK7cPq+nWbe6e7yZx4CUUUq0IEwCbNJGGjijtAbUIg=,tag:fVTWEouX2ZGS+lAGuz4Dtw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
