github_token: ENC[AES256_GCM,data:eKBighkK/mmTB2Y8+k/2bIaf07Xxn4iz40s85VsLHMnnOTfg6zoAXQ==,iv:LHTRpaBIqDpYURdWMQS7khPyqEZyy3LgMVE1gk2SqSg=,tag:wc5XyR8VSlxc8sJ5nq6wPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcE1ZQjZPWG9GYlFWUDBG
            RkFMd1BCOHpIWVE1MllJSTJNdHFWb0N0Z1dFCkwrNVF3L2ZHTHJoYkM4dnd3RW1m
            VDY4eUFxcVNvT0oySGZpT3A1RDFHZ3cKLS0tIHZVYnA0Wk1MVnZxMDNRK1YyeG5U
            L2JjOGdoNzQ4eEl6Sy9wYjVNbTBFZW8KMHz2WkIbdBkZBOQ2l8S3dFLn6A+zxiMt
            B8vjY+55Y9tlcMeLF9BoH1adxm3huKQEP52Sn6eOEZemnAmIBrXh9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r9eq9v6a0d42wud7whenfv4f29jgfv5t7qpzra0p36d6twsj2dhslppu56
    lastmodified: "2026-05-21T17:43:31Z"
    mac: ENC[AES256_GCM,data:Bsi2gvs5fgp3BnTsU8Fyx0XxNVpz3axrh1aaB4vQgQlm6zKzC4S7A+8Gs5mOFCUcsUAwIy8i76EpSzMXSZGJpOdZXNV7hTjGcLKE7YMjiylKB2imklAaOytPTo4nuzSa4wxD9cKcw0sPRrMDM9P79ZGdR/xpEsOJ2nA9SuLXEsM=,iv:RAn7rM5Z0J+I5q8AemYGM8q5FD3440DpAHSNN2E9PRQ=,tag:ecO8u5JBGRyk0Qcn+p5exQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.0
